
"""
Reward definitions for different learning styles.
"""

STYLES = {
    "Standard (Curriculum)": {
        "type": "curriculum",
        "description": "Progressive learning: Food -> Walls -> Enemies -> Strategy",
        "stages": {
            1: {
                "name": "FOOD_VECTOR",
                "gamma": 0.85,
                "food_reward": 3.0,
                "food_shaping": 0.5,
                "survival": 0.1,
                "survival_escalation": 0.0,
                "death_wall": -15,
                "death_snake": -15,
                "straight_penalty": 0.0,
                "length_bonus": 0.0,
                "wall_alert_dist": 2000,
                "enemy_alert_dist": 800,
                "wall_proximity_penalty": 0.3,
                "enemy_proximity_penalty": 0.0,
                "enemy_approach_penalty": 0.0,
                "boost_penalty": 0.0,
                "max_steps": 300,
                # COMPOUND: must eat AND survive
                "promote_metric": "compound",
                "promote_conditions": {
                    "avg_food": 5,
                    "avg_steps": 50,
                },
                "promote_window": 200,
            },
            2: {
                "name": "WALL_AVOID",
                "gamma": 0.93,
                "food_reward": 2.0,
                "food_shaping": 0.15,
                "survival": 0.5,
                "survival_escalation": 0.01,
                "death_wall": -40,
                "death_snake": -20,
                "straight_penalty": 0.0,
                "length_bonus": 0.0,
                "wall_alert_dist": 2500,
                "enemy_alert_dist": 800,
                "wall_proximity_penalty": 1.5,
                "enemy_proximity_penalty": 0.0,
                "enemy_approach_penalty": 0.0,
                "boost_penalty": 0.0,
                "max_steps": 500,
                "promote_metric": "avg_steps",
                "promote_threshold": 55,
                "promote_wall_death_max": 0.12,
                "promote_window": 200,
            },
            3: {
                "name": "ENEMY_AVOID",
                "gamma": 0.97,
                "food_reward": 5.0,
                "food_shaping": 0.1,
                "survival": 1.2,
                "survival_escalation": 0.015,
                "death_wall": -40,
                "death_snake": -40,
                "straight_penalty": 0.0,
                "length_bonus": 0.0,
                "wall_alert_dist": 2000,
                "enemy_alert_dist": 1500,
                "wall_proximity_penalty": 0.5,
                "enemy_proximity_penalty": 1.5,
                "enemy_approach_penalty": 0.5,
                "boost_penalty": 0.3,
                "max_steps": 1000,
                "promote_metric": "avg_steps",
                "promote_threshold": 200,
                "promote_window": 300,
            },
            4: {
                "name": "MASS_MANAGEMENT",
                "gamma": 0.97,
                "food_reward": 5.0,
                "food_shaping": 0.1,
                "survival": 0.3,
                "survival_escalation": 0.005,
                "death_wall": -35,
                "death_snake": -25,
                "straight_penalty": 0.0,
                "length_bonus": 0.02,
                "wall_alert_dist": 2000,
                "enemy_alert_dist": 1000,
                "wall_proximity_penalty": 0.5,
                "enemy_proximity_penalty": 0.8,
                "enemy_approach_penalty": 0.3,
                "boost_penalty": 0.0,
                "max_steps": 2000,
                "promote_metric": None,
                "promote_threshold": None,
                "promote_window": 100,
            },
        }
    },
    "Aggressive (Hunter)": {
        "type": "static",
        "description": "High reward for eating and moving towards food. Low survival bonus.",
        "config": {
            "name": "HUNTER",
            "food_reward": 20.0,
            "food_shaping": 0.05,
            "survival": 0.0,
            "death_wall": -50,
            "death_snake": -10, # Risk taking allowed
            "straight_penalty": 0.0,
            "length_bonus": 0.0,
            "wall_alert_dist": 1500,
            "enemy_alert_dist": 700,
            "wall_proximity_penalty": 0.05,
            "enemy_proximity_penalty": 0.05,
            "max_steps": 99999,
        }
    },
    "Defensive (Safe)": {
        "type": "static",
        "description": "High survival bonus and heavy death penalties.",
        "config": {
            "name": "SAFE",
            "food_reward": 5.0,
            "food_shaping": 0.005,
            "survival": 0.5,
            "death_wall": -50,
            "death_snake": -40,
            "straight_penalty": 0.05,
            "length_bonus": 0.0,
            "wall_alert_dist": 2200,
            "enemy_alert_dist": 900,
            "wall_proximity_penalty": 0.2,
            "enemy_proximity_penalty": 0.15,
            "max_steps": 99999,
        }
    },
    "Explorer (Anti-Float)": {
        "type": "static",
        "description": "Penalizes staying still/floating. Forces movement.",
        "config": {
            "name": "EXPLORER",
            "food_reward": 5.0,
            "food_shaping": 0.05,   # Strongly encourage seeking food
            "survival": 0.05,
            "death_wall": -50,
            "death_snake": -40,
            "straight_penalty": 0.1, # Force turning/activity
            "length_bonus": 0.0,
            "wall_alert_dist": 1800,
            "enemy_alert_dist": 800,
            "wall_proximity_penalty": 0.5,
            "enemy_proximity_penalty": 0.1,
            "max_steps": 99999,
        }
    }
}
